# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy for dev

on:
    push:
        branches:
            - 'master' # 只针对 dev 分支
        paths:
            - '.github/workflows/*'
            - '__test__/**'
            - 'src/**'
            - 'config/*'
            - 'Dockerfile'
            - 'docker-compose.yml'
            - 'nginx.conf'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.ZX_ID_RSA}}" > ~/.ssh/id_rsa # secret 在这里配置 https://github.com/filway/admin-fe/settings/secrets
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan "139.155.58.207" >> ~/.ssh/known_hosts
            - name: deploy # 部署
              run: |
                  ssh zhouxiao@139.155.58.207 "
                    # 【注意】手动创建 /home/zhouxiao/filway-lego 目录
                    # 然后 git clone https://username:password@github.com/filway/admin-fe.git -b dev （私有项目，使用 github 用户名和密码下载）
                    # 记得删除 origin ，否则会暴露 github 密码

                    cd /home/zhouxiao/filway-lego/admin-fe;
                    git remote add origin https://filway:${{secrets.ZX_PASSWORD}}@github.com/filawy/admin-fe.git;
                    git checkout dev;
                    git pull origin dev; # 重新下载最新代码
                    git remote remove origin; # 删除 origin ，否则会暴露 github 密码

                    # 构建 prd-dev
                    yarn install;
                    yarn run build-dev;

                    # 启动 docker
                    docker-compose build admin-fe; # 和 docker-compose.yml service 名字一致
                    docker-compose up -d;
                  "
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa
